name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug
labels: ['bug', 'state: need triage']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
        How do you trigger this bug?
        Please walk us through it step by step.
        Please provide a screenshot if possible.
    validations:
      required: true
