name: ⚠️ Release
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-release:
    name: Release
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.58.0
        with:
          fetch-depth: 0
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/node@v1.58.0
      - uses: taiga-family/ci/actions/setup/config/git@v1.58.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/config/npm@v1.58.0
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}

      - run: npx release-it --increment --ci
        env:
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - name: Publish
        run: npx nx run-many --target publish --all --output-style=stream

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
